apiVersion: v1
kind: Namespace
metadata:
  name: fargate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: fargate
spec:
  selector:
    matchLabels:
      run: my-nginx-fargate
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx-fargate
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
